/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teletalk_jserver_util_FileSystemInfo */

#ifndef _Included_com_teletalk_jserver_util_SystemInfo
#define _Included_com_teletalk_jserver_util_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: libraryLoaded */
/*
 * Class:     com_teletalk_jserver_util_FileSystemInfo
 * Method:    getDiskFreeSpaceNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_teletalk_jserver_util_SystemInfo_getDiskFreeSpaceNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
